# --- Toolchain Definitions ---
AS = riscv32-unknown-elf-as -march=rv32i -mabi=ilp32
GCC = riscv32-unknown-elf-gcc -march=rv32i -mabi=ilp32 -c
LD = riscv32-unknown-elf-ld
OBJCOPY = riscv32-unknown-elf-objcopy
HEXDUMP = hexdump

# --- Paths ---
# You may need to adjust this path to your system
PATH_TO_LIBGCC = ~/informatica/risc-v/install/rv32i/lib/gcc/riscv32-unknown-elf/11.1.0
LIBGCC_A = $(PATH_TO_LIBGCC)/libgcc.a